[package]
name = "leptos_sync_ssr"
version = "0.0.1"
authors = ["Tommy Yu <tommy.yu@auckland.ac.nz>"]
license = "MIT"
repository = "https://github.com/metatoaster/leptos_sync_ssr"
description = "A helper for the Leptos Rust web framework for synchronizing server-side resources"
readme = "README.md"
rust-version = "1.80"
edition = "2021"

[dependencies]
leptos = { version = "0.8.0-beta" }
serde = { version = "1", optional = true }
tokio = { version = "1", features = ["sync"], optional = true }

[features]
default = []
portlet = [
    "dep:serde",
]
ssr = [
    "leptos/ssr",
    "dep:tokio",
]
