extend = [
    { path = "../cargo-make/cargo-leptos-webdriver-test.toml" },
]

[env]
CLIENT_PROCESS_NAME = "nav_portlet"

[tasks.test-ui]
cwd = "./e2e"
command = "cargo"
args = ["make", "test-ui", "${@}"]
